export const HDM4_INPUT_TABLES = [
  {
    title: "Representative Vehicles",
    unit: "Fleet class parameters",
    columns: ["Vehicle class", "GVW tonnes", "ESAL factor", "Fleet share", "DUCAR use"],
    rows: [
      ["Motorcycle", "0.2", "0.0003", "28%", "Rural access and market-day mobility"],
      ["Car / Sedan", "1.5", "0.0004", "22%", "Passenger time and light vehicle VOC"],
      ["Pickup / SUV", "2.8", "0.002", "14%", "District supervision and rural services"],
      ["Minibus", "3.5", "0.01", "12%", "Public transport accessibility"],
      ["Medium Bus", "7.0", "0.18", "6%", "School, commuter and inter-town movement"],
      ["Medium Truck", "11.0", "0.45", "8%", "Agricultural and construction freight"],
      ["Heavy Truck", "22.0", "2.1", "5%", "Accelerated pavement loading"],
      ["Articulated Truck", "40.0", "4.5", "3%", "Freight corridor stress"],
      ["Tanker", "36.0", "3.8", "2%", "High-consequence loading and safety risk"],
    ],
  },
  {
    title: "Climate Zones",
    unit: "Screening assumptions",
    columns: ["Zone", "Rainfall mm/year", "Moisture class", "Temperature range", "Road risk"],
    rows: [
      ["Lake Victoria Crescent", "1,200-1,500", "Wet", "18-28 C", "Drainage and edge-break risk"],
      ["Western Highlands", "1,000-1,800", "Wet-humid", "12-25 C", "Slope and landslide risk"],
      ["Northern Savanna", "800-1,200", "Sub-humid", "20-35 C", "Seasonal gravel loss"],
      ["Karamoja Semi-arid", "500-800", "Dry", "22-38 C", "Dust, corrugation and water scarcity"],
      ["Eastern Highlands", "1,200-2,000", "Humid", "15-27 C", "Culvert sizing and erosion"],
      ["Central Plateau", "1,100-1,400", "Sub-humid", "18-30 C", "Routine drainage maintenance"],
    ],
  },
  {
    title: "Axle Loading",
    unit: "Vehicle mass and overloading",
    columns: ["Vehicle type", "Legal limit t", "Observed t", "Overload share", "Model effect"],
    rows: [
      ["2-axle truck", "18.0", "21.4", "38%", "Rutting and roughness progression"],
      ["3-axle truck", "25.0", "28.6", "42%", "Structural fatigue"],
      ["6-axle articulated", "48.0", "54.2", "35%", "High ESAL growth"],
      ["Tanker", "44.0", "47.8", "28%", "Safety and pavement stress"],
      ["Tipper", "22.0", "26.1", "45%", "Construction material haul damage"],
      ["Bus", "16.0", "15.2", "5%", "Passenger vehicle loading"],
    ],
  },
  {
    title: "Road Deterioration Models",
    unit: "Calibration placeholders",
    columns: ["Distress", "HDM-4 model family", "Calibration factor", "Uganda placeholder", "Decision use"],
    rows: [
      ["Cracking initiation", "RDME", "Kci", "1.15", "Seal or overlay timing"],
      ["Cracking progression", "RDME", "Kcp", "1.08", "Periodic maintenance trigger"],
      ["Ravelling initiation", "RDME", "Kvi", "0.95", "Surface treatment selection"],
      ["Rutting", "RDME", "Krs", "1.22", "Truck loading sensitivity"],
      ["Roughness progression", "RDME", "Kgm", "1.10", "VOC and travel-time impact"],
      ["Potholing", "RDME", "Kpt", "1.30", "Safety and emergency works"],
      ["Edge break", "RDME", "Ked", "1.05", "Shoulder and drainage works"],
      ["Texture loss", "RDME", "Ktd", "0.98", "Skid resistance and safety"],
    ],
  },
  {
    title: "Work Effects Models",
    unit: "Treatment response",
    columns: ["Treatment", "IRI reset", "Service life", "Cost USD/km", "Programme implication"],
    rows: [
      ["Routine patching", "Reduce 0.5", "1 year", "800-1,500", "Short-term safety and passability"],
      ["Single / double reseal", "3.5", "5-7 years", "15,000-25,000", "Preventive preservation"],
      ["50 mm asphalt overlay", "2.8", "8-10 years", "85,000-120,000", "Capacity and VOC savings"],
      ["Reconstruction", "2.0", "15-20 years", "250,000-450,000", "Major capital renewal"],
      ["Gravel resheeting", "8.0", "3-4 years", "12,000-18,000", "Community access restoration"],
      ["Spot regravelling", "Reduce 2.0", "2 years", "5,000-8,000", "Localised maintainability"],
    ],
  },
  {
    title: "Road User Effects Models",
    unit: "Economic effects",
    columns: ["Component", "Input dependency", "Uganda calibration", "Benefit channel", "Output"],
    rows: [
      ["Fuel VOC", "Speed, IRI, gradient", "Fuel UGX 5,200/L", "Vehicle operating cost", "VOC savings"],
      ["Tyres", "IRI, texture, loading", "Truck tyre UGX 1.85M", "Vehicle resources", "Resource savings"],
      ["Maintenance parts", "Roughness and speed", "Labour UGX 15K/hr", "Fleet maintenance", "VOC savings"],
      ["Travel time", "Speed-flow type", "Purpose valuation", "User time", "Time savings"],
      ["Accidents", "Traffic and risk class", "Fatality cost UGX 680M", "Safety", "Crash-cost savings"],
      ["Emissions", "Speed and fuel use", "CO2e damage placeholder", "Climate externality", "Emissions cost"],
    ],
  },
  {
    title: "Unit Costs by Surface Type",
    unit: "Planning cost range",
    columns: ["Surface", "Construction USD/km", "Periodic maintenance", "Routine maintenance", "DUCAR note"],
    rows: [
      ["Asphalt concrete", "350,000-600,000", "8,500", "2,800", "Urban and high-demand links"],
      ["Double bituminous seal", "180,000-280,000", "5,200", "2,200", "Low-volume sealed roads"],
      ["Single bituminous seal", "120,000-180,000", "4,800", "2,000", "Access roads with moderate demand"],
      ["Gravel", "45,000-80,000", "3,500", "1,800", "Most DUCAR access roads"],
      ["Earth", "15,000-30,000", "2,000", "1,200", "Lowest-cost access with high climate risk"],
      ["Concrete", "500,000-800,000", "3,200", "1,500", "Special urban/industrial sections"],
    ],
  },
  {
    title: "Traffic Flow and Speed Types",
    unit: "Capacity assumptions",
    columns: ["Road type", "Free-flow speed", "Capacity veh/hr", "Peak hour share", "Seasonal factor"],
    rows: [
      ["2-lane paved rural", "80-100 km/h", "1,200", "8-12%", "1.05-1.15"],
      ["2-lane unpaved", "40-60 km/h", "600", "6-10%", "1.10-1.30"],
      ["Urban arterial", "40-60 km/h", "1,800", "10-14%", "1.02-1.05"],
      ["CBD/KCCA road", "25-45 km/h", "1,200", "12-16%", "1.01-1.03"],
      ["Mountain/escarpment", "30-50 km/h", "800", "6-10%", "1.10-1.25"],
    ],
  },
  {
    title: "Economic Analysis Parameters",
    unit: "Appraisal defaults",
    columns: ["Parameter", "Value", "Unit", "Sensitivity range", "Use"],
    rows: [
      ["Discount rate", "12", "%", "8-15", "NPV and EIRR appraisal"],
      ["Analysis period", "20", "years", "10-25", "Lifecycle comparison"],
      ["Base year", "2026", "year", "Update annually", "Cost and traffic base"],
      ["Currency", "UGX", "currency", "USD conversion optional", "Budget integration"],
      ["Price contingency", "5", "%", "0-10", "Planning uncertainty"],
      ["Minimum EIRR", "12", "%", "10-15", "Selection gate"],
    ],
  },
];

export const HDM4_INDICATORS = [
  ["Fleet loading", "Representative vehicle and ESAL inputs", 84],
  ["Climate stress", "Rainfall, temperature and drainage exposure", 76],
  ["Deterioration readiness", "Roughness, cracking, rutting and pothole models", 81],
  ["Work effects", "Treatment reset, service life and unit-cost assumptions", 79],
  ["Road user effects", "VOC, time, safety and emissions benefit streams", 73],
  ["Economic parameters", "Discount, period, contingency and threshold settings", 88],
];
